from . import patient_visit
from . import res_partner
from . import prescription
from . import lab_job
from . import insurance_claim
from . import submission_batch
from . import payment_entry
from . import stock_location
# from . import stock_movement
from . import remake
from . import external_vendor
from . import ceo_dashboard
from . import product_template
from . import res_company
from . import config_settings
from . import account_move
from . import extended_models
from . import equipment_transfer_request
from . import equipment_transfer_request_lines