from odoo import models, fields, api, _
from odoo.exceptions import UserError
import base64
from io import BytesIO


class SubmissionBatch(models.Model):
    _name = "eyekei.submission.batch"
    _description = "Insurance Submission Batch"
    _inherit = ["mail.thread"]

    name = fields.Char("Batch Number", readonly=True, default="New")
    serial_number = fields.Char("Serial Number", readonly=True)
    submission_date = fields.Date("Submission Date", default=fields.Date.today)
    insurance_company_id = fields.Many2one(
        "eyekei.insurance.company", "Insurance Company"
    )

    # Claims in this batch
    claim_ids = fields.One2many(
        "eyekei.insurance.claim", "submission_batch_id", "Claims"
    )
    claim_count = fields.Integer("Number of Claims", compute="_compute_counts")
    total_amount = fields.Float("Total Amount", compute="_compute_counts")

    # Generated PDF
    pdf_generated = fields.Boolean("PDF Generated")
    pdf_file = fields.Binary("Submission PDF")
    pdf_filename = fields.Char("PDF Filename")

    # Company branding for letterhead
    generated_by = fields.Many2one(
        "res.users", "Generated By", default=lambda self: self.env.user
    )
    company_stamp_area = fields.Boolean("Include Stamp Area", default=True)

    state = fields.Selection(
        [
            ("draft", "Draft"),
            ("generated", "PDF Generated"),
            ("submitted", "Submitted to Insurance"),
            ("acknowledged", "Acknowledged"),
        ],
        default="draft",
    )

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get("name", "New") == "New":
                vals["name"] = self.env["ir.sequence"].next_by_code(
                    "eyekei.submission.batch"
                )
                vals["serial_number"] = self.env["ir.sequence"].next_by_code(
                    "eyekei.submission.serial"
                )
        return super().create(vals_list)

    @api.depends("claim_ids", "claim_ids.billed_amount")
    def _compute_counts(self):
        for batch in self:
            batch.claim_count = len(batch.claim_ids)
            batch.total_amount = sum(batch.claim_ids.mapped("billed_amount"))

    def action_generate_pdf(self):
        """Generate submission PDF with company letterhead"""
        self.ensure_one()
        if not self.claim_ids:
            raise UserError(_("No claims selected for this batch."))

        # Generate PDF using QWeb report
        report_action = self.env.ref("eyekei_eyewear.action_report_submission_batch")
        pdf_content, _ = report_action._render_qweb_pdf(self.id)

        self.write(
            {
                "pdf_file": base64.b64encode(pdf_content),
                "pdf_filename": f"Submission_{self.serial_number}.pdf",
                "pdf_generated": True,
                "state": "generated",
            }
        )

        # Update all claims to submitted
        self.claim_ids.action_submit(batch_id=self.id)

        return {
            "type": "ir.actions.act_url",
            "url": f"/web/content/eyekei.submission.batch/{self.id}/pdf_file/{self.pdf_filename}?download=1",
            "target": "self",
        }

    def action_mark_submitted(self):
        self.write({"state": "submitted"})
        for claim in self.claim_ids:
            claim.write({"state": "submitted"})

    def action_submit_batch(self):
        """Mark all claims in batch as submitted"""
        self.ensure_one()
        if self.state != 'generated':
            raise UserError(_("Please generate the PDF before submitting."))
        self.claim_ids.action_submit(batch_id=self.id)
        self.write({"state": "submitted"})
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Batch Submitted'),
                'message': '%s claims submitted in batch %s.' % (self.claim_count, self.name),
                'type': 'success',
                'sticky': False,
            }
        }
