import uuid
from datetime import timedelta
from odoo import models, fields, api


class ResCompany(models.Model):
    _inherit = 'res.company'

    api_authorization_tier = fields.Selection(
        selection=[
            ('trial', 'Trial'),
            ('premium', 'Premium'),
        ],
        string='API Authorization Tier',
        default='trial',
    )

    subscription_code = fields.Char(
        string='Subscription Code',
        copy=False,
        readonly=True,
        index=True,
        help="Unique generated registration and subscription code."
    )

    subscription_status = fields.Selection(
        selection=[
            ('active', 'Active'),
            ('past_due', 'Past Due'),
            ('cancelled', 'Cancelled'),
            ('expired', 'Expired'),
            ('unpaid', 'Unpaid'),
        ],
        string='Subscription Status',
        default='active',
    )

    api_tier_expiration_date = fields.Date(
        string='Tier Expiration Date',
        readonly=True,
        help="Autogenerated expiration date based on tier requirements."
    )
    is_verified = fields.Boolean(string='Is Verified', default=False)
    verification_token = fields.Char(string='Verification Token', copy=False, index=True)
    activated_core_module_ids = fields.Many2many(
        'ir.module.module',
        'res_company_core_module_rel',
        'company_id',
        'module_id',
        string='Activated Tenant Modules',
        domain=[('application', '=', True)],
        help="Core Odoo applications enabled for this specific company tenant."
    )

    _sql_constraints = [
        ('subscription_code_unique', 'unique(subscription_code)',
         'The Subscription Code must be unique across all companies!')
    ]
    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if not vals.get('subscription_code'):
                vals['subscription_code'] = self.env['ir.sequence'].next_by_code('res.company.subscription.code') or '/'
            if not vals.get('verification_token'):
                vals['verification_token'] = uuid.uuid4().hex

            if vals.get('api_authorization_tier', 'trial') == 'trial':
                vals['api_tier_expiration_date'] = fields.Date.today() + timedelta(days=30)
            else:
                vals['api_tier_expiration_date'] = False

        return super(ResCompany, self).create(vals_list)